"""
generate_catalog.py
===================
One-time utility: scans the fabwave CAD library and writes db/cad_catalog.py,
a static Python module that lists every CAD file with its category.

Run ONCE while the fabwave folder is available:
    uv run python -m db.generate_catalog

After generation, the fabwave folder can be deleted.
init_db.py imports cad_catalog.py instead of scanning fabwave directly.
"""

import pathlib
import sys

HERE = pathlib.Path(__file__).parent          # db/
ROOT = HERE.parent                            # project root
FABWAVE_DIR = ROOT / "fabwave"
OUTPUT = HERE / "cad_catalog.py"


def scan(fabwave_dir: pathlib.Path) -> list[tuple[str, str]]:
    """Return sorted list of (category_folder, cad_file_name) for every CAD file."""
    seen_names: set[str] = set()
    entries: list[tuple[str, str]] = []

    for p in sorted(fabwave_dir.rglob("*")):
        if p.suffix.lower() not in (".stp", ".step"):
            continue
        if not p.is_file():
            continue

        # Category: two directories above the file  (…/CATEGORY/STEP/file)
        category = p.parent.parent.name

        cad_name = p.name
        if cad_name in seen_names:
            cad_name = p.relative_to(fabwave_dir).as_posix()
        seen_names.add(cad_name)

        entries.append((category, cad_name))

    return entries


def write_catalog(entries: list[tuple[str, str]], output: pathlib.Path) -> None:
    lines = [
        '"""',
        "cad_catalog.py  –  AUTO-GENERATED by db/generate_catalog.py",
        "Do not edit by hand. Re-run generate_catalog.py to refresh.",
        '"""',
        "",
        "# (category_folder, cad_file_name)",
        "CAD_FILES: list[tuple[str, str]] = [",
    ]
    for category, name in entries:
        lines.append(f'    ({category!r}, {name!r}),')
    lines += ["]", ""]
    output.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    if not FABWAVE_DIR.exists():
        sys.exit(f"ERROR: fabwave directory not found: {FABWAVE_DIR}")

    print(f"Scanning {FABWAVE_DIR} …")
    entries = scan(FABWAVE_DIR)
    print(f"  Found {len(entries)} CAD files.")

    write_catalog(entries, OUTPUT)
    print(f"  Written → {OUTPUT}")
    print("You can now delete the fabwave folder.")


if __name__ == "__main__":
    main()
