"""
init_db.py  EPLM/ERP demo database initialization
====================================================
CAD file list source (in priority order):
  1. db/cad_catalog.py   Estatic list generated by db/generate_catalog.py
                          (fabwave folder NOT required at runtime)
  2. fabwave/            Elive scan fallback (only if cad_catalog.py absent)

To prepare for deleting the fabwave folder:
    uv run python -m db.generate_catalog   # generates db/cad_catalog.py
    uv run python -m db.init_db            # uses cad_catalog.py

Production order mix (global target):
  70 % in_house  |  25 % outsource  |  5 % purchase
Orders per part: 0 E (random, seeded per file for reproducibility).
"""

import argparse
import calendar
import datetime
import math
import pathlib
import random
import sys

sys.path.insert(0, str(pathlib.Path(__file__).parent.parent))

from db.database import engine, SessionLocal
from db.models import Base, Part, PartStructure, Vendor, Customer, ProductionOrder, PurchaseItem

# ---------------------------------------------------------------------------
# CAD file list: prefer static catalog, fall back to live fabwave scan
# ---------------------------------------------------------------------------
FABWAVE_DIR = pathlib.Path(__file__).parent.parent / "fabwave"


def _load_cad_files() -> list[tuple[str, str]]:
    """Return list of (category_folder, cad_file_name) from catalog or fabwave."""
    try:
        from db.cad_catalog import CAD_FILES  # type: ignore
        print(f"  Using static catalog: {len(CAD_FILES)} files (db/cad_catalog.py)")
        return CAD_FILES
    except ImportError:
        pass

    if not FABWAVE_DIR.exists():
        raise FileNotFoundError(
            "Neither db/cad_catalog.py nor the fabwave/ directory was found.\n"
            "Run 'uv run python -m db.generate_catalog' while fabwave/ is present."
        )

    print(f"  cad_catalog.py not found  Escanning {FABWAVE_DIR} …")
    seen: set[str] = set()
    entries: list[tuple[str, str]] = []
    for p in sorted(FABWAVE_DIR.rglob("*")):
        if p.suffix.lower() not in (".stp", ".step") or not p.is_file():
            continue
        category = p.parent.parent.name
        name = p.name
        if name in seen:
            name = p.relative_to(FABWAVE_DIR).as_posix()
        seen.add(name)
        entries.append((category, name))
    print(f"  Found {len(entries)} CAD files.")
    return entries

# ---------------------------------------------------------------------------
# Material pools
# ---------------------------------------------------------------------------
_MAT_IRON    = ["Carbon Steel S45C", "Carbon Steel SS400", "FC250 (Gray Cast Iron)"]
# S45C: representative machine structural steel
# SS400: representative general structural steel
# FC250: representative cast iron (common in cast parts)

_MAT_SUS     = ["SUS304", "SUS316"]
# SUS304: general-purpose stainless steel
# SUS316: enhanced corrosion resistance (chemical/marine environments)

_MAT_AL      = ["A5052 (Al)", "A6061 (Al)"]
# A5052: prioritizes formability
# A6061: prioritizes strength and mechanical properties

_MAT_PLASTIC = ["POM", "Nylon 66", "PTFE"]
# POM: dimensional precision and versatility
# Nylon 66: wear resistance and toughness
# PTFE: heat resistance, chemical resistance, low friction

# ---------------------------------------------------------------------------
# Category rules
# Each tuple: (keyword_in_folder_name_lowercase, config_dict)
# Rules are tested in order; first match wins.
# "" matches everything ↁEuse as final fallback.
# ---------------------------------------------------------------------------
# po_mix: [in_house_pct, outsource_pct, purchase_pct]  (must sum to 1.0)
# vendor_outsource / vendor_purchase: list of vendor IDs to pick from
# ---------------------------------------------------------------------------
CATEGORY_RULES = [
    # ---- Piping --------------------------------------------------------
    # Primary: stainless (corrosion resistance for fluid lines)
    ("pipe_fitting", dict(
        prefix="FTG",  name="Pipe Fitting",
        mat_primary=_MAT_SUS, mat_secondary=_MAT_IRON,
        weight=(0.05, 0.55),
        vendor_outsource=["V006"], vendor_purchase=["V006"],
        po_mix=[0.75, 0.20, 0.05], draw_prefix="DWG-FTG",
        revisions=["A", "B"],
    )),
    ("pipe_joint", dict(
        prefix="JNT",  name="Pipe Joint",
        mat_primary=_MAT_SUS, mat_secondary=_MAT_IRON,
        weight=(0.08, 0.45),
        vendor_outsource=["V006"], vendor_purchase=["V006"],
        po_mix=[0.75, 0.20, 0.05], draw_prefix="DWG-JNT",
        revisions=["A", "B"],
    )),
    ("pipe", dict(
        prefix="PIPE", name="Pipe",
        mat_primary=_MAT_SUS, mat_secondary=_MAT_IRON,
        weight=(0.30, 3.50),
        vendor_outsource=["V006", "V001"], vendor_purchase=["V006"],
        po_mix=[0.75, 0.20, 0.05], draw_prefix="DWG-PIPE",
        revisions=["A", "B"],
    )),
    # ---- Rotating / mechanical -----------------------------------------
    # Primary: iron/steel (strength, machinability for shafts and rollers)
    ("roller", dict(
        prefix="ROLL", name="Conveyor Roller",
        mat_primary=_MAT_IRON, mat_secondary=_MAT_SUS,
        weight=(0.50, 6.00),
        vendor_outsource=["V004", "V001"], vendor_purchase=["V004"],
        po_mix=[0.75, 0.20, 0.05], draw_prefix="DWG-ROLL",
        revisions=["A", "B", "C"],
    )),
    ("rotary_shaft", dict(
        prefix="SHFT", name="Rotary Shaft",
        mat_primary=["Carbon Steel S45C"], mat_secondary=["Carbon Steel SS400"] + _MAT_SUS,
        weight=(0.50, 18.00),
        vendor_outsource=["V001", "V008"], vendor_purchase=["V001"],
        po_mix=[0.75, 0.20, 0.05], draw_prefix="DWG-SHFT",
        revisions=["A", "B"],
    )),
    ("shaft_collar", dict(
        prefix="COLL", name="Shaft Collar",
        mat_primary=_MAT_IRON, mat_secondary=_MAT_SUS,
        weight=(0.05, 0.85),
        vendor_outsource=["V001", "V004"], vendor_purchase=["V001", "V004"],
        po_mix=[0.75, 0.20, 0.05], draw_prefix="DWG-COLL",
        revisions=["A"],
    )),
    # ---- Fasteners / standard hardware --------------------------------
    # Primary: stainless (corrosion resistance for washers/screws/bolts)
    ("sleeve washer", dict(
        prefix="SWSH", name="Sleeve Washer",
        mat_primary=_MAT_SUS, mat_secondary=_MAT_IRON,
        weight=(0.01, 0.20),
        vendor_outsource=["V001", "V003"], vendor_purchase=["V003"],
        po_mix=[0.75, 0.20, 0.05], draw_prefix="DWG-SWSH",
        revisions=["A"],
    )),
    ("washer", dict(
        prefix="WSHR", name="Washer",
        mat_primary=_MAT_SUS, mat_secondary=_MAT_IRON,
        weight=(0.001, 0.12),
        vendor_outsource=["V003"], vendor_purchase=["V003"],
        po_mix=[0.75, 0.20, 0.05], draw_prefix="DWG-WSHR",
        revisions=["A"],
    )),
    ("socket_head_screw", dict(
        prefix="SCRS", name="Socket Head Cap Screw",
        mat_primary=_MAT_SUS, mat_secondary=_MAT_IRON,
        weight=(0.002, 0.06),
        vendor_outsource=["V003"], vendor_purchase=["V003"],
        po_mix=[0.75, 0.20, 0.05], draw_prefix="DWG-SCRS",
        revisions=["A"],
    )),
    ("socket-c", dict(
        prefix="SCRC", name="Socket Cap Screw",
        mat_primary=_MAT_SUS, mat_secondary=_MAT_IRON,
        weight=(0.002, 0.06),
        vendor_outsource=["V003"], vendor_purchase=["V003"],
        po_mix=[0.75, 0.20, 0.05], draw_prefix="DWG-SCRC",
        revisions=["A"],
    )),
    ("slotted_flat_head", dict(
        prefix="SFHS", name="Slotted Flat Head Screw",
        mat_primary=_MAT_SUS, mat_secondary=_MAT_IRON,
        weight=(0.001, 0.03),
        vendor_outsource=["V003"], vendor_purchase=["V003"],
        po_mix=[0.75, 0.20, 0.05], draw_prefix="DWG-SFHS",
        revisions=["A"],
    )),
    # Hex head screws: carbon steel preferred for high-strength applications
    ("hex_head_s", dict(
        prefix="HEXS", name="Hex Head Screw",
        mat_primary=_MAT_IRON, mat_secondary=_MAT_SUS,
        weight=(0.005, 0.12),
        vendor_outsource=["V003"], vendor_purchase=["V003"],
        po_mix=[0.75, 0.20, 0.05], draw_prefix="DWG-HEXS",
        revisions=["A"],
    )),
    ("headless", dict(
        prefix="HDLS", name="Headless Set Screw",
        mat_primary=_MAT_SUS, mat_secondary=_MAT_IRON,
        weight=(0.001, 0.02),
        vendor_outsource=["V003"], vendor_purchase=["V003"],
        po_mix=[0.75, 0.20, 0.05], draw_prefix="DWG-HDLS",
        revisions=["A"],
    )),
    ("thumb_scre", dict(
        prefix="THBS", name="Thumb Screw",
        mat_primary=_MAT_SUS, mat_secondary=_MAT_IRON,
        weight=(0.005, 0.06),
        vendor_outsource=["V003"], vendor_purchase=["V003"],
        po_mix=[0.75, 0.20, 0.05], draw_prefix="DWG-THBS",
        revisions=["A"],
    )),
    ("eyesbolt", dict(
        prefix="EYEB", name="Eye Bolt",
        mat_primary=_MAT_SUS, mat_secondary=_MAT_IRON,
        weight=(0.05, 0.60),
        vendor_outsource=["V003", "V001"], vendor_purchase=["V003"],
        po_mix=[0.75, 0.20, 0.05], draw_prefix="DWG-EYEB",
        revisions=["A"],
    )),
    ("holebolt", dict(
        prefix="HOLB", name="Hole Bolt",
        mat_primary=_MAT_SUS, mat_secondary=_MAT_IRON,
        weight=(0.03, 0.25),
        vendor_outsource=["V003", "V001"], vendor_purchase=["V003"],
        po_mix=[0.75, 0.20, 0.05], draw_prefix="DWG-HOLB",
        revisions=["A"],
    )),
    ("cotter_pin", dict(
        prefix="COTP", name="Cotter Pin",
        mat_primary=_MAT_SUS, mat_secondary=_MAT_IRON,
        weight=(0.001, 0.06),
        vendor_outsource=["V003"], vendor_purchase=["V003"],
        po_mix=[0.75, 0.20, 0.05], draw_prefix="DWG-COTP",
        revisions=["A"],
    )),
    # Retaining rings: carbon steel preferred for spring-like properties
    ("external", dict(
        prefix="ERNG", name="External Retaining Ring",
        mat_primary=_MAT_IRON, mat_secondary=_MAT_SUS,
        weight=(0.002, 0.06),
        vendor_outsource=["V003", "V001"], vendor_purchase=["V003"],
        po_mix=[0.75, 0.20, 0.05], draw_prefix="DWG-ERNG",
        revisions=["A"],
    )),
    # Note: "bolt" must come AFTER "eyesbolt" / "holebolt"
    # Hex bolts: carbon steel preferred for structural fastening
    ("bolt", dict(
        prefix="BOLT", name="Hex Bolt",
        mat_primary=_MAT_IRON, mat_secondary=_MAT_SUS,
        weight=(0.01, 0.20),
        vendor_outsource=["V003"], vendor_purchase=["V003"],
        po_mix=[0.75, 0.20, 0.05], draw_prefix="DWG-BOLT",
        revisions=["A"],
    )),
    ("nut", dict(
        prefix="NUT",  name="Hex Nut",
        mat_primary=_MAT_IRON, mat_secondary=_MAT_SUS,
        weight=(0.003, 0.06),
        vendor_outsource=["V003"], vendor_purchase=["V003"],
        po_mix=[0.75, 0.20, 0.05], draw_prefix="DWG-NUT",
        revisions=["A"],
    )),
    # ---- Bearings / bushings ------------------------------------------
    # Bearings: high-carbon steel (S45C as proxy); bushings: plastics for self-lubrication
    ("bearing", dict(
        prefix="BRG",  name="Ball Bearing",
        mat_primary=["Carbon Steel S45C"], mat_secondary=["Carbon Steel SS400"],
        weight=(0.05, 2.00),
        vendor_outsource=["V002"], vendor_purchase=["V002"],
        po_mix=[0.75, 0.20, 0.05], draw_prefix="DWG-BRG",
        revisions=["A"],
    )),
    ("bushing_da", dict(
        prefix="DBSH", name="Damping Bushing",
        mat_primary=_MAT_PLASTIC, mat_secondary=_MAT_AL,
        weight=(0.05, 0.60),
        vendor_outsource=["V006", "V008"], vendor_purchase=["V006"],
        po_mix=[0.75, 0.20, 0.05], draw_prefix="DWG-DBSH",
        revisions=["A"],
    )),
    # Note: "bushing_da" before "bushing"
    ("bushing", dict(
        prefix="BUSH", name="Bushing",
        mat_primary=_MAT_PLASTIC, mat_secondary=_MAT_AL,
        weight=(0.02, 0.60),
        vendor_outsource=["V001", "V008"], vendor_purchase=["V003", "V001"],
        po_mix=[0.75, 0.20, 0.05], draw_prefix="DWG-BUSH",
        revisions=["A"],
    )),
    ("collet", dict(
        prefix="COLT", name="Collet",
        mat_primary=["Carbon Steel S45C"], mat_secondary=_MAT_SUS,
        weight=(0.02, 0.25),
        vendor_outsource=["V002", "V001"], vendor_purchase=["V002"],
        po_mix=[0.75, 0.20, 0.05], draw_prefix="DWG-COLT",
        revisions=["A"],
    )),
    # ---- Seals / gaskets -----------------------------------------------
    # Primary: PTFE/plastic (chemical resistance, compressibility for sealing)
    ("gasket", dict(
        prefix="GASK", name="Gasket",
        mat_primary=_MAT_PLASTIC, mat_secondary=_MAT_SUS,
        weight=(0.005, 0.15),
        vendor_outsource=["V006"], vendor_purchase=["V006"],
        po_mix=[0.75, 0.20, 0.05], draw_prefix="DWG-GASK",
        revisions=["A"],
    )),
    ("grommet", dict(
        prefix="GROM", name="Grommet",
        mat_primary=_MAT_PLASTIC, mat_secondary=_MAT_AL,
        weight=(0.001, 0.06),
        vendor_outsource=["V006"], vendor_purchase=["V006"],
        po_mix=[0.75, 0.20, 0.05], draw_prefix="DWG-GROM",
        revisions=["A"],
    )),
    ("o_ring", dict(
        prefix="ORING", name="O-Ring",
        mat_primary=_MAT_PLASTIC, mat_secondary=_MAT_SUS,
        weight=(0.001, 0.025),
        vendor_outsource=["V006"], vendor_purchase=["V006"],
        po_mix=[0.75, 0.20, 0.05], draw_prefix="DWG-ORING",
        revisions=["A"],
    )),
    # ---- Gears / power transmission ------------------------------------
    # Primary: carbon steel S45C (hardness, wear resistance for gears/shafts)
    ("keyway_sha", dict(
        prefix="KWSH", name="Keyway Shaft",
        mat_primary=["Carbon Steel S45C"], mat_secondary=["Carbon Steel SS400"] + _MAT_SUS,
        weight=(0.30, 12.00),
        vendor_outsource=["V001", "V008"], vendor_purchase=["V001"],
        po_mix=[0.75, 0.20, 0.05], draw_prefix="DWG-KWSH",
        revisions=["A", "B"],
    )),
    ("machine_ke", dict(
        prefix="MKEY", name="Machine Key",
        mat_primary=_MAT_IRON, mat_secondary=_MAT_SUS,
        weight=(0.005, 0.12),
        vendor_outsource=["V001", "V003"], vendor_purchase=["V003"],
        po_mix=[0.75, 0.20, 0.05], draw_prefix="DWG-MKEY",
        revisions=["A"],
    )),
    ("miter ge", dict(
        prefix="MTRG", name="Miter Gear",
        mat_primary=["Carbon Steel S45C"], mat_secondary=["Carbon Steel SS400", "FC250 (Gray Cast Iron)"],
        weight=(0.10, 2.50),
        vendor_outsource=["V005", "V008"], vendor_purchase=["V005"],
        po_mix=[0.75, 0.20, 0.05], draw_prefix="DWG-MTRG",
        revisions=["A", "B"],
    )),
    ("idler sp", dict(
        prefix="IDSP", name="Idler Sprocket",
        mat_primary=_MAT_IRON, mat_secondary=_MAT_AL,
        weight=(0.20, 2.50),
        vendor_outsource=["V005", "V004"], vendor_purchase=["V005"],
        po_mix=[0.75, 0.20, 0.05], draw_prefix="DWG-IDSP",
        revisions=["A"],
    )),
    ("sprocket", dict(
        prefix="SPKT", name="Sprocket",
        mat_primary=_MAT_IRON, mat_secondary=_MAT_AL,
        weight=(0.20, 3.50),
        vendor_outsource=["V005", "V004"], vendor_purchase=["V005"],
        po_mix=[0.75, 0.20, 0.05], draw_prefix="DWG-SPKT",
        revisions=["A", "B"],
    )),
    ("gear rod", dict(
        prefix="GRDR", name="Gear Rod",
        mat_primary=["Carbon Steel S45C"], mat_secondary=["Carbon Steel SS400", "FC250 (Gray Cast Iron)"],
        weight=(0.20, 4.00),
        vendor_outsource=["V005", "V001"], vendor_purchase=["V005"],
        po_mix=[0.75, 0.20, 0.05], draw_prefix="DWG-GRDR",
        revisions=["A"],
    )),
    # Note: "gear" after "gear rod", "miter ge"
    ("gear", dict(
        prefix="GEAR", name="Spur Gear",
        mat_primary=["Carbon Steel S45C"], mat_secondary=["Carbon Steel SS400", "FC250 (Gray Cast Iron)"],
        weight=(0.10, 6.00),
        vendor_outsource=["V005", "V008"], vendor_purchase=["V005"],
        po_mix=[0.75, 0.20, 0.05], draw_prefix="DWG-GEAR",
        revisions=["A", "B"],
    )),
    # ---- Structural / enclosures ---------------------------------------
    # Brackets/plates: carbon steel (SS400 for structural rigidity)
    # Enclosures/routing: aluminum (lightweight, good formability)
    ("bracket", dict(
        prefix="BKT",  name="Mounting Bracket",
        mat_primary=_MAT_IRON, mat_secondary=_MAT_AL,
        weight=(0.10, 4.00),
        vendor_outsource=["V007", "V008"], vendor_purchase=["V007"],
        po_mix=[0.75, 0.20, 0.05], draw_prefix="DWG-BKT",
        revisions=["A", "B", "C"],
    )),
    ("box", dict(
        prefix="ENCL", name="Enclosure Box",
        mat_primary=_MAT_AL, mat_secondary=_MAT_IRON,
        weight=(0.30, 6.00),
        vendor_outsource=["V007", "V008"], vendor_purchase=["V007"],
        po_mix=[0.75, 0.20, 0.05], draw_prefix="DWG-ENCL",
        revisions=["A", "B"],
    )),
    ("rectangu", dict(
        prefix="RECT", name="Rectangular Plate",
        mat_primary=_MAT_IRON, mat_secondary=_MAT_AL,
        weight=(0.20, 12.00),
        vendor_outsource=["V007", "V003"], vendor_purchase=["V007"],
        po_mix=[0.75, 0.20, 0.05], draw_prefix="DWG-RECT",
        revisions=["A", "B"],
    )),
    ("routing", dict(
        prefix="RTBK", name="Routing Bracket",
        mat_primary=_MAT_AL, mat_secondary=_MAT_IRON,
        weight=(0.10, 1.80),
        vendor_outsource=["V007", "V008"], vendor_purchase=["V007"],
        po_mix=[0.75, 0.20, 0.05], draw_prefix="DWG-RTBK",
        revisions=["A"],
    )),
    ("strut ch", dict(
        prefix="STRC", name="Strut Channel",
        mat_primary=_MAT_IRON, mat_secondary=_MAT_SUS,
        weight=(0.30, 6.00),
        vendor_outsource=["V007", "V003"], vendor_purchase=["V003"],
        po_mix=[0.75, 0.20, 0.05], draw_prefix="DWG-STRC",
        revisions=["A"],
    )),
    ("tag hold", dict(
        prefix="TAGHD", name="Tag Holder",
        mat_primary=_MAT_SUS, mat_secondary=_MAT_IRON,
        weight=(0.02, 0.25),
        vendor_outsource=["V007", "V003"], vendor_purchase=["V003"],
        po_mix=[0.75, 0.20, 0.05], draw_prefix="DWG-TAGHD",
        revisions=["A"],
    )),
    ("webbing", dict(
        prefix="WBCL", name="Webbing Clip",
        mat_primary=_MAT_SUS, mat_secondary=_MAT_IRON,
        weight=(0.02, 0.25),
        vendor_outsource=["V007", "V003"], vendor_purchase=["V003"],
        po_mix=[0.75, 0.20, 0.05], draw_prefix="DWG-WBCL",
        revisions=["A"],
    )),
    ("wide gri", dict(
        prefix="WDGR", name="Wide Grip",
        mat_primary=_MAT_SUS, mat_secondary=_MAT_IRON,
        weight=(0.05, 0.60),
        vendor_outsource=["V007", "V003"], vendor_purchase=["V003"],
        po_mix=[0.75, 0.20, 0.05], draw_prefix="DWG-WDGR",
        revisions=["A"],
    )),
    # ---- Fallback ------------------------------------------------------
    ("", dict(
        prefix="PART", name="Mechanical Part",
        mat_primary=_MAT_IRON, mat_secondary=_MAT_SUS,
        weight=(0.05, 3.00),
        vendor_outsource=["V001", "V007", "V008"], vendor_purchase=["V003"],
        po_mix=[0.75, 0.20, 0.05], draw_prefix="DWG-PART",
        revisions=["A"],
    )),
]


def get_config(folder_name: str) -> dict:
    """Return the first matching category config for *folder_name*."""
    fn = folder_name.lower()
    for keyword, cfg in CATEGORY_RULES:
        if keyword in fn:
            return cfg
    return CATEGORY_RULES[-1][1]


# ---------------------------------------------------------------------------
# Tables
# ---------------------------------------------------------------------------

def create_tables():
    Base.metadata.drop_all(bind=engine)
    Base.metadata.create_all(bind=engine)


# ---------------------------------------------------------------------------
# Seed
# ---------------------------------------------------------------------------

def seed(db, locale: str = "JP"):
    today = datetime.date.today()

    def future(days: int) -> datetime.date:
        return today + datetime.timedelta(days=days)

    def past(years: int = 0, months: int = 0) -> datetime.date:
        yr = today.year - years
        mo = today.month - months
        while mo <= 0:
            mo += 12
            yr -= 1
        return datetime.date(yr, mo, min(today.day, calendar.monthrange(yr, mo)[1]))

    # -----------------------------------------------------------------------
    # Vendors
    # -----------------------------------------------------------------------
    vendors = [
        Vendor(vendor_id="V001", vendor_name="Yamada Precision Machining Ltd.",
               specialty="Rotary shafts, collars, precision turning",
               country="JP", rating=4.8, typical_lead_time_days=14),
        Vendor(vendor_id="V002", vendor_name="Toyo Bearing Industries Co., Ltd.",
               specialty="Rolling bearings, precision mechanical parts",
               country="JP", rating=4.9, typical_lead_time_days=7),
        Vendor(vendor_id="V003", vendor_name="McMaster-Carr Supply Company",
               specialty="Fasteners, standard hardware, consumables",
               country="US", rating=4.7, typical_lead_time_days=10),
        Vendor(vendor_id="V004", vendor_name="Misumi Group Inc.",
               specialty="Conveyor rollers, linear motion, custom standards",
               country="JP", rating=4.6, typical_lead_time_days=5),
        Vendor(vendor_id="V005", vendor_name="Hitachi Metals Machinery Co., Ltd.",
               specialty="Gears, sprockets, heat-treated components",
               country="JP", rating=4.5, typical_lead_time_days=21),
        Vendor(vendor_id="V006", vendor_name="Parker Hannifin Japan Ltd.",
               specialty="Pipe fittings, O-rings, seals, fluid control",
               country="US", rating=4.7, typical_lead_time_days=14),
        Vendor(vendor_id="V007", vendor_name="Mitsubishi Materials Corp.",
               specialty="Brackets, structural parts, sheet metal fabrication",
               country="JP", rating=4.4, typical_lead_time_days=18),
        Vendor(vendor_id="V008", vendor_name="Kyowa Industrial Co., Ltd.",
               specialty="Custom machining, prototypes, special orders",
               country="JP", rating=4.3, typical_lead_time_days=28),
    ]
    db.add_all(vendors)
    db.flush()

    # -----------------------------------------------------------------------
    # Customers (取引先 / 発注元)
    # locale="JP" : 日本企業10社  locale="KR" : 韓国企業10社  locale="CN" : 中国企業10社
    # -----------------------------------------------------------------------
    if locale == "CN":
        customers = [
            Customer(customer_id="C001", company_name="上海精密机械有限公司",
                     contact_name="张伟", address1="上海市浦东新区张江高科技园区1号",
                     address2="浦东新区, 上海市", email="zhang@sh-precision.com.cn",
                     phone="021-1234-5678"),
            Customer(customer_id="C002", company_name="北京航天工程技术有限公司",
                     contact_name="李芳", address1="北京市海淀区中关村科技园2-3号",
                     address2="海淀区, 北京市", email="li@bj-aerospace-eng.com.cn",
                     phone="010-2345-6789"),
            Customer(customer_id="C003", company_name="广州机电制造股份有限公司",
                     contact_name="王强", address1="广州市天河区高新技术产业开发区3-5号",
                     address2="天河区, 广州市", email="wang@gz-mechatronics.com.cn",
                     phone="020-3456-7890"),
            Customer(customer_id="C004", company_name="深圳智能装备科技有限公司",
                     contact_name="刘洋", address1="深圳市南山区科技园南区4-7号",
                     address2="南山区, 深圳市", email="liu@sz-intelligent.com.cn",
                     phone="0755-456-7890"),
            Customer(customer_id="C005", company_name="成都西部精工股份有限公司",
                     contact_name="陈静", address1="成都市高新区天府大道5-9号",
                     address2="高新区, 成都市", email="chen@cd-westprecision.com.cn",
                     phone="028-567-8901"),
            Customer(customer_id="C006", company_name="武汉重型机械有限公司",
                     contact_name="赵磊", address1="武汉市武昌区东湖高新技术开发区6-11号",
                     address2="武昌区, 武汉市", email="zhao@wh-heavymach.com.cn",
                     phone="027-678-9012"),
            Customer(customer_id="C007", company_name="苏州纳米精密制造有限公司",
                     contact_name="孙燕", address1="苏州市工业园区独墅湖科教创新区7-13号",
                     address2="工业园区, 苏州市", email="sun@sz-nanoprecision.com.cn",
                     phone="0512-789-0123"),
            Customer(customer_id="C008", company_name="天津滨海新区机械工程有限公司",
                     contact_name="周建国", address1="天津市滨海新区经济技术开发区8-15号",
                     address2="滨海新区, 天津市", email="zhou@tj-binhai-mech.com.cn",
                     phone="022-890-1234"),
            Customer(customer_id="C009", company_name="西安航空动力技术有限公司",
                     contact_name="吴雪梅", address1="西安市高新技术产业开发区9-17号",
                     address2="高新区, 西安市", email="wu@xa-aviationpower.com.cn",
                     phone="029-901-2345"),
            Customer(customer_id="C010", company_name="杭州数控机床有限公司",
                     contact_name="郑浩然", address1="杭州市滨江区高新技术产业园10-19号",
                     address2="滨江区, 杭州市", email="zheng@hz-cncmachine.com.cn",
                     phone="0571-012-3456"),
        ]
    elif locale == "KR":
        customers = [
            Customer(customer_id="C001", company_name="한국정밀기계 주식회사",
                     contact_name="김민준", address1="서울특별시 강남구 테헤란로 1-1",
                     address2="강남구, 서울특별시", email="kim@kpm-kr.co.kr",
                     phone="02-1234-5678"),
            Customer(customer_id="C002", company_name="대한엔지니어링 주식회사",
                     contact_name="이서연", address1="부산광역시 해운대구 센텀중앙로 2-3",
                     address2="해운대구, 부산광역시", email="lee@daehan-eng.co.kr",
                     phone="051-234-5678"),
            Customer(customer_id="C003", company_name="서울정공 주식회사",
                     contact_name="박지호", address1="서울특별시 구로구 디지털로 3-5",
                     address2="구로구, 서울특별시", email="park@seoul-sg.co.kr",
                     phone="02-3456-7890"),
            Customer(customer_id="C004", company_name="인천테크노 주식회사",
                     contact_name="최수진", address1="인천광역시 남동구 논현로 4-7",
                     address2="남동구, 인천광역시", email="choi@incheon-techno.co.kr",
                     phone="032-456-7890"),
            Customer(customer_id="C005", company_name="경기메카트로닉스 주식회사",
                     contact_name="정우성", address1="경기도 수원시 영통구 광교로 5-9",
                     address2="영통구, 수원시, 경기도", email="jung@gg-mec.co.kr",
                     phone="031-567-8901"),
            Customer(customer_id="C006", company_name="부산산업기계 주식회사",
                     contact_name="강은지", address1="부산광역시 사상구 사상로 6-11",
                     address2="사상구, 부산광역시", email="kang@busan-im.co.kr",
                     phone="051-678-9012"),
            Customer(customer_id="C007", company_name="대구정밀공업 주식회사",
                     contact_name="윤도현", address1="대구광역시 달서구 성서공단로 7-13",
                     address2="달서구, 대구광역시", email="yoon@daegu-precision.co.kr",
                     phone="053-789-0123"),
            Customer(customer_id="C008", company_name="울산시스템공업 주식회사",
                     contact_name="임지수", address1="울산광역시 남구 산업로 8-15",
                     address2="남구, 울산광역시", email="lim@ulsan-si.co.kr",
                     phone="052-890-1234"),
            Customer(customer_id="C009", company_name="광주엔지니어링 주식회사",
                     contact_name="한승민", address1="광주광역시 광산구 하남산단로 9-17",
                     address2="광산구, 광주광역시", email="han@gwangju-eng.co.kr",
                     phone="062-901-2345"),
            Customer(customer_id="C010", company_name="대전기계공업 주식회사",
                     contact_name="오미래", address1="대전광역시 유성구 테크노밸리로 10-19",
                     address2="유성구, 대전광역시", email="oh@daejeon-ki.co.kr",
                     phone="042-012-3456"),
        ]
    else:  # JP (default)
        customers = [
            Customer(customer_id="C001", company_name="株式会社山田製作所",
                     contact_name="山田 一郎", address1="東京都千代田区丸の内1-1-1",
                     address2="千代田区, 東京都", email="yamada@yamada-ss.co.jp",
                     phone="03-1234-5678"),
            Customer(customer_id="C002", company_name="東洋エンジニアリング株式会社",
                     contact_name="鈴木 次郎", address1="神奈川県横浜市中区港町2-3-4",
                     address2="横浜市中区, 神奈川県", email="suzuki@toyo-eng.co.jp",
                     phone="045-234-5678"),
            Customer(customer_id="C003", company_name="大阪精機工業株式会社",
                     contact_name="田中 三郎", address1="大阪府大阪市西区阿波座3-5-6",
                     address2="大阪市西区, 大阪府", email="tanaka@osaka-seiki.co.jp",
                     phone="06-3456-7890"),
            Customer(customer_id="C004", company_name="名古屋テクノ株式会社",
                     contact_name="伊藤 花子", address1="愛知県名古屋市中村区名駅4-7-8",
                     address2="名古屋市中村区, 愛知県", email="ito@nagoya-techno.co.jp",
                     phone="052-456-7890"),
            Customer(customer_id="C005", company_name="九州メカトロニクス株式会社",
                     contact_name="渡辺 太郎", address1="福岡県福岡市博多区博多駅前5-9-10",
                     address2="福岡市博多区, 福岡県", email="watanabe@kyushu-mec.co.jp",
                     phone="092-567-8901"),
            Customer(customer_id="C006", company_name="北海道産業機械株式会社",
                     contact_name="佐藤 洋子", address1="北海道札幌市中央区北一条西6-11-12",
                     address2="札幌市中央区, 北海道", email="sato@hokkaido-im.co.jp",
                     phone="011-678-9012"),
            Customer(customer_id="C007", company_name="東北精密工業株式会社",
                     contact_name="高橋 健一", address1="宮城県仙台市青葉区一番町7-13-14",
                     address2="仙台市青葉区, 宮城県", email="takahashi@tohoku-seimitsu.co.jp",
                     phone="022-789-0123"),
            Customer(customer_id="C008", company_name="中部機器製造株式会社",
                     contact_name="小林 美咲", address1="静岡県浜松市中区砂山町8-15-16",
                     address2="浜松市中区, 静岡県", email="kobayashi@chubu-kiki.co.jp",
                     phone="053-890-1234"),
            Customer(customer_id="C009", company_name="関西エレクトロメカ株式会社",
                     contact_name="加藤 拓也", address1="兵庫県神戸市中央区三宮町9-17-18",
                     address2="神戸市中央区, 兵庫県", email="kato@kansai-em.co.jp",
                     phone="078-901-2345"),
            Customer(customer_id="C010", company_name="四国システム工業株式会社",
                     contact_name="吉田 裕子", address1="香川県高松市番町10-19-20",
                     address2="高松市, 香川県", email="yoshida@shikoku-si.co.jp",
                     phone="087-012-3456"),
        ]
    db.add_all(customers)
    db.flush()

    customer_ids = [c.customer_id for c in customers]

    # -----------------------------------------------------------------------
    # Load CAD file list (catalog or live scan)
    # -----------------------------------------------------------------------
    raw = _load_cad_files()   # list of (category, cad_file_name)

    # -----------------------------------------------------------------------
    # Build Part records
    # -----------------------------------------------------------------------
    parts: list[Part] = []
    part_cfgs: list[dict] = []        # parallel list, same index as parts
    prefix_counters: dict[str, int] = {}

    for category, cad_name in raw:
        cfg = get_config(category)
        prefix = cfg["prefix"]
        prefix_counters[prefix] = prefix_counters.get(prefix, 0) + 1
        seq = prefix_counters[prefix]
        part_id = f"{prefix}-{seq:04d}"

        # Per-file seeded RNG so the output is deterministic
        rng = random.Random(cad_name)

        mat_primary   = cfg["mat_primary"]
        mat_secondary = cfg.get("mat_secondary", [])
        # 75 % from category-preferred primary materials, 25 % from secondary
        if mat_secondary and rng.random() < 0.75:
            mat = rng.choice(mat_primary)
        else:
            mat = rng.choice(mat_secondary if mat_secondary else mat_primary)
        weight  = round(rng.uniform(*cfg["weight"]), 3)
        rev     = rng.choice(cfg["revisions"])
        drawing = f"{cfg['draw_prefix']}-{seq:04d}"

        status_roll = rng.random()
        status = ("active" if status_roll < 0.85
                  else "under_review" if status_roll < 0.95
                  else "obsolete")

        yr = today.year - rng.randint(0, 4)
        mo = today.month - rng.randint(0, 11)
        while mo <= 0:
            mo += 12; yr -= 1
        created_at = datetime.date(yr, mo, min(today.day, calendar.monthrange(yr, mo)[1]))

        part_name = f"{cfg['name']} {part_id}"

        parts.append(Part(
            part_id=part_id,
            part_name=part_name,
            revision=rev,
            material=mat,
            weight_kg=weight,
            drawing_number=drawing,
            cad_file_name=cad_name,
            created_at=created_at,
            status=status,
        ))
        part_cfgs.append(cfg)

    db.add_all(parts)
    db.flush()

    # -----------------------------------------------------------------------
    # Sample BOM assemblies
    # Group first parts by prefix for illustration
    # -----------------------------------------------------------------------
    first_by_prefix: dict[str, str] = {}  # prefix -> part_id
    for part in parts:
        pfx = part.part_id.rsplit("-", 1)[0]
        if pfx not in first_by_prefix:
            first_by_prefix[pfx] = part.part_id

    def bom_if_exists(parent_prefix: str, child_prefix: str, qty: int):
        parent = first_by_prefix.get(parent_prefix)
        child  = first_by_prefix.get(child_prefix)
        if parent and child and parent != child:
            return PartStructure(parent_part_id=parent, child_part_id=child, quantity=qty)
        return None

    bom_candidates = [
        # Conveyor roller assembly
        bom_if_exists("ROLL", "SHFT",  1),
        bom_if_exists("ROLL", "BRG",   2),
        bom_if_exists("ROLL", "COLL",  2),
        bom_if_exists("ROLL", "BOLT",  4),
        bom_if_exists("ROLL", "NUT",   4),
        bom_if_exists("ROLL", "WSHR",  8),
        # Gear drive unit
        bom_if_exists("GEAR", "KWSH",  1),
        bom_if_exists("GEAR", "BRG",   2),
        bom_if_exists("GEAR", "BUSH",  1),
        bom_if_exists("GEAR", "HEXS",  4),
        bom_if_exists("GEAR", "MKEY",  1),
        # Sprocket drive
        bom_if_exists("SPKT", "SHFT",  1),
        bom_if_exists("SPKT", "BRG",   2),
        bom_if_exists("SPKT", "SCRS",  4),
        # Pipe assembly
        bom_if_exists("PIPE", "FTG",   2),
        bom_if_exists("PIPE", "JNT",   1),
        bom_if_exists("PIPE", "ORING", 4),
        bom_if_exists("PIPE", "GASK",  2),
        bom_if_exists("PIPE", "BKT",   2),
        bom_if_exists("PIPE", "BOLT",  8),
        # Enclosure
        bom_if_exists("ENCL", "BKT",   4),
        bom_if_exists("ENCL", "SCRS",  8),
        bom_if_exists("ENCL", "GROM",  4),
    ]
    bom = [b for b in bom_candidates if b is not None]
    db.add_all(bom)
    db.flush()

    # -----------------------------------------------------------------------
    # Production orders  (0 E per part, 70/25/5 mix)
    # -----------------------------------------------------------------------
    QUALITY_WEIGHTS = [0.78, 0.17, 0.05]   # passed / pending / failed
    QUALITY_CHOICES = ["passed", "pending", "failed"]

    # Number of orders distribution (weights for 0,1,2,3,4,5)
    ORDER_COUNT_WEIGHTS = [8, 22, 28, 22, 12, 8]

    orders: list[ProductionOrder] = []
    order_seq = 1

    for part, cfg in zip(parts, part_cfgs):
        rng = random.Random(part.cad_file_name + "_po")

        n_orders = rng.choices(range(6), weights=ORDER_COUNT_WEIGHTS)[0]

        # Base unit cost for this part; larger lots get same or lower price
        # KR locale: amounts in KRW (~10x JPY)  CN locale: amounts in CNY (~1/20 JPY)  JP locale: amounts in JPY
        if locale == "KR":
            base_unit_cost = round(rng.uniform(200.0, 80000.0), 0)
        elif locale == "CN":
            base_unit_cost = round(rng.uniform(1.0, 400.0), 0)
        else:
            base_unit_cost = round(rng.uniform(20.0, 8000.0), 0)

        for _ in range(n_orders):
            # Production type
            roll = rng.random()
            pmix = cfg["po_mix"]
            if roll < pmix[0]:
                ptype     = "in_house"
                vendor_id = None
            elif roll < pmix[0] + pmix[1]:
                ptype     = "outsource"
                vendor_id = rng.choice(cfg["vendor_outsource"])
            else:
                ptype     = "purchase"
                vendor_id = rng.choice(cfg["vendor_purchase"])

            qty = rng.randint(5, 300)
            # Quantity discount: monotonically increases with lot size (log scale, capped at 30%)
            discount_rate = min(0.30, 0.08 * math.log(qty / 5.0 + 1.0))
            unit_cost = max(1.0, round(base_unit_cost * (1.0 - discount_rate), 0))
            if ptype == "purchase":
                lead_days = rng.randint(2, 5)
                del_days  = rng.randint(2, 7)
            elif ptype == "in_house":
                lead_days = rng.randint(4, 20)
                del_days  = rng.randint(5, 25)
            else:  # outsource
                lead_days = rng.randint(6, 30)
                del_days  = rng.randint(7, 35)
            quality   = rng.choices(QUALITY_CHOICES, weights=QUALITY_WEIGHTS)[0]

            orders.append(ProductionOrder(
                order_id        = f"PO-{order_seq:06d}",
                part_id         = part.part_id,
                production_type = ptype,
                vendor_id       = vendor_id,
                customer_id     = rng.choice(customer_ids),
                quantity        = qty,
                unit_cost_jpy   = float(unit_cost),
                lead_time_days  = lead_days,
                delivery_date   = today + datetime.timedelta(days=del_days),
                quality_result  = quality,
                notes           = None,
            ))
            order_seq += 1

    db.add_all(orders)
    db.flush()

    # -----------------------------------------------------------------------
    # Purchase items  Eone catalog entry per part that has any "purchase" order
    # -----------------------------------------------------------------------
    purchase_parts: set[str] = {
        o.part_id for o in orders if o.production_type == "purchase"
    }
    purchase_items: list[PurchaseItem] = []
    pi_seq = 1

    for part, cfg in zip(parts, part_cfgs):
        if part.part_id not in purchase_parts:
            continue
        rng = random.Random(part.cad_file_name + "_pi")
        vendor_id = rng.choice(cfg["vendor_purchase"])
        # KR locale: catalog price in KRW (~10x JPY)  CN locale: in CNY (~1/20 JPY)  JP locale: in JPY
        if locale == "KR":
            catalog_price = round(rng.uniform(100.0, 50000.0), 0)
        elif locale == "CN":
            catalog_price = round(rng.uniform(1.0, 250.0), 0)
        else:
            catalog_price = round(rng.uniform(10.0, 5000.0), 0)
        moq  = rng.choice([10, 25, 50, 100, 200, 500])
        lead = rng.randint(2, 5)  # 購入品: 2-5日

        purchase_items.append(PurchaseItem(
            item_id          = f"PI-{pi_seq:05d}",
            part_id          = part.part_id,
            vendor_id        = vendor_id,
            catalog_price_jpy= float(catalog_price),
            min_order_qty    = moq,
            lead_time_days   = lead,
        ))
        pi_seq += 1

    db.add_all(purchase_items)
    db.commit()

    # -----------------------------------------------------------------------
    # Summary
    # -----------------------------------------------------------------------
    total_po = len(orders)
    in_house = sum(1 for o in orders if o.production_type == "in_house")
    outsource= sum(1 for o in orders if o.production_type == "outsource")
    purchase = sum(1 for o in orders if o.production_type == "purchase")

    print(
        f"\nDatabase seeded successfully:\n"
        f"  Customers        : {len(customers)}\n"
        f"  Vendors          : {len(vendors)}\n"
        f"  Parts            : {len(parts)}\n"
        f"  BOM rows         : {len(bom)}\n"
        f"  Production orders: {total_po} "
        f"(in_house {in_house} / outsource {outsource} / purchase {purchase})\n"
        f"  Purchase items   : {len(purchase_items)}\n"
    )


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Initialize PLM/ERP demo database")
    parser.add_argument(
        "--locale",
        choices=["JP", "KR", "CN"],
        default="JP",
        help="Customer locale and currency: JP=日本円/日本企業 (default), KR=韓国ウォン/韓国企業, CN=人民元/中国企業",
    )
    args = parser.parse_args()

    locale_label = {"JP": "JPY / Japanese customers", "KR": "KRW / Korean customers", "CN": "CNY / Chinese customers"}
    print(f"Locale: {args.locale}  ({locale_label[args.locale]})")
    print("Creating tables …")
    create_tables()
    db = SessionLocal()
    try:
        seed(db, locale=args.locale)
    except Exception as exc:
        db.rollback()
        print(f"ERROR: {exc}")
        raise
    finally:
        db.close()
    print("Database ready.")
