"""
init_db.py – PLM/ERP demo database initialization
====================================================
CAD file list source (in priority order):
  1. db/cad_catalog.py  – static list generated by db/generate_catalog.py
                          (fabwave folder NOT required at runtime)
  2. fabwave/           – live scan fallback (only if cad_catalog.py absent)

To prepare for deleting the fabwave folder:
    uv run python -m db.generate_catalog   # generates db/cad_catalog.py
    uv run python -m db.init_db            # uses cad_catalog.py

Production order mix (global target):
  70 % in_house  |  25 % outsource  |  5 % purchase
Orders per part: 0–5 (random, seeded per file for reproducibility).
"""

import calendar
import datetime
import pathlib
import random
import sys

sys.path.insert(0, str(pathlib.Path(__file__).parent.parent))

from db.database import engine, SessionLocal
from db.models import Base, Part, PartStructure, Vendor, ProductionOrder, PurchaseItem

# ---------------------------------------------------------------------------
# CAD file list: prefer static catalog, fall back to live fabwave scan
# ---------------------------------------------------------------------------
FABWAVE_DIR = pathlib.Path(__file__).parent.parent / "fabwave"


def _load_cad_files() -> list[tuple[str, str]]:
    """Return list of (category_folder, cad_file_name) from catalog or fabwave."""
    try:
        from db.cad_catalog import CAD_FILES  # type: ignore
        print(f"  Using static catalog: {len(CAD_FILES)} files (db/cad_catalog.py)")
        return CAD_FILES
    except ImportError:
        pass

    if not FABWAVE_DIR.exists():
        raise FileNotFoundError(
            "Neither db/cad_catalog.py nor the fabwave/ directory was found.\n"
            "Run 'uv run python -m db.generate_catalog' while fabwave/ is present."
        )

    print(f"  cad_catalog.py not found – scanning {FABWAVE_DIR} …")
    seen: set[str] = set()
    entries: list[tuple[str, str]] = []
    for p in sorted(FABWAVE_DIR.rglob("*")):
        if p.suffix.lower() not in (".stp", ".step") or not p.is_file():
            continue
        category = p.parent.parent.name
        name = p.name
        if name in seen:
            name = p.relative_to(FABWAVE_DIR).as_posix()
        seen.add(name)
        entries.append((category, name))
    print(f"  Found {len(entries)} CAD files.")
    return entries

# ---------------------------------------------------------------------------
# Material pools
# ---------------------------------------------------------------------------
_MAT_STEEL  = ["Carbon Steel S45C", "Carbon Steel S35C", "Carbon Steel SS400"]
_MAT_SUS    = ["SUS304", "SUS316", "SUS316L"]
_MAT_SCM    = ["SCM440", "SCM435", "SCM415"]
_MAT_BRG    = ["SUJ2", "SUJ2 (HRC 60+)"]
_MAT_RUBBER = ["NBR", "FKM", "EPDM", "Silicone"]
_MAT_BRASS  = ["C3604BD (Brass)", "C3771BD (Brass)"]
_MAT_AL     = ["A5052 (Al)", "A6061 (Al)"]
_MAT_CAST   = ["FC250 (Gray Cast Iron)", "FCD400 (Ductile Iron)"]
_MAT_PLASTIC= ["Nylon 66", "POM", "PTFE"]

# ---------------------------------------------------------------------------
# Category rules
# Each tuple: (keyword_in_folder_name_lowercase, config_dict)
# Rules are tested in order; first match wins.
# "" matches everything → use as final fallback.
# ---------------------------------------------------------------------------
# po_mix: [in_house_pct, outsource_pct, purchase_pct]  (must sum to 1.0)
# vendor_outsource / vendor_purchase: list of vendor IDs to pick from
# ---------------------------------------------------------------------------
CATEGORY_RULES = [
    # ---- Fasteners / standard hardware --------------------------------
    ("pipe_fitting", dict(
        prefix="FTG",  name="Pipe Fitting",
        mat=_MAT_SUS,  weight=(0.05, 0.55),
        vendor_outsource=["V006"], vendor_purchase=["V006"],
        po_mix=[0.70, 0.25, 0.05], draw_prefix="DWG-FTG",
        revisions=["A", "B"],
    )),
    ("pipe_joint", dict(
        prefix="JNT",  name="Pipe Joint",
        mat=_MAT_SUS,  weight=(0.08, 0.45),
        vendor_outsource=["V006"], vendor_purchase=["V006"],
        po_mix=[0.70, 0.25, 0.05], draw_prefix="DWG-JNT",
        revisions=["A", "B"],
    )),
    ("pipe", dict(
        prefix="PIPE", name="Pipe",
        mat=_MAT_SUS + ["SGP", "STPG370"],  weight=(0.30, 3.50),
        vendor_outsource=["V006", "V001"], vendor_purchase=["V006"],
        po_mix=[0.70, 0.25, 0.05], draw_prefix="DWG-PIPE",
        revisions=["A", "B"],
    )),
    ("roller", dict(
        prefix="ROLL", name="Conveyor Roller",
        mat=_MAT_STEEL + _MAT_SUS, weight=(0.50, 6.00),
        vendor_outsource=["V004", "V001"], vendor_purchase=["V004"],
        po_mix=[0.70, 0.25, 0.05], draw_prefix="DWG-ROLL",
        revisions=["A", "B", "C"],
    )),
    ("rotary_shaft", dict(
        prefix="SHFT", name="Rotary Shaft",
        mat=_MAT_SCM + _MAT_STEEL, weight=(0.50, 18.00),
        vendor_outsource=["V001", "V008"], vendor_purchase=["V001"],
        po_mix=[0.70, 0.25, 0.05], draw_prefix="DWG-SHFT",
        revisions=["A", "B"],
    )),
    ("shaft_collar", dict(
        prefix="COLL", name="Shaft Collar",
        mat=_MAT_STEEL + _MAT_SUS, weight=(0.05, 0.85),
        vendor_outsource=["V001", "V004"], vendor_purchase=["V001", "V004"],
        po_mix=[0.70, 0.25, 0.05], draw_prefix="DWG-COLL",
        revisions=["A"],
    )),
    ("sleeve washer", dict(
        prefix="SWSH", name="Sleeve Washer",
        mat=_MAT_SUS + _MAT_BRASS, weight=(0.01, 0.20),
        vendor_outsource=["V001", "V003"], vendor_purchase=["V003"],
        po_mix=[0.70, 0.25, 0.05], draw_prefix="DWG-SWSH",
        revisions=["A"],
    )),
    ("washer", dict(
        prefix="WSHR", name="Washer",
        mat=_MAT_SUS + _MAT_STEEL, weight=(0.001, 0.12),
        vendor_outsource=["V003"], vendor_purchase=["V003"],
        po_mix=[0.70, 0.25, 0.05], draw_prefix="DWG-WSHR",
        revisions=["A"],
    )),
    ("socket_head_screw", dict(
        prefix="SCRS", name="Socket Head Cap Screw",
        mat=_MAT_SUS + _MAT_SCM, weight=(0.002, 0.06),
        vendor_outsource=["V003"], vendor_purchase=["V003"],
        po_mix=[0.70, 0.25, 0.05], draw_prefix="DWG-SCRS",
        revisions=["A"],
    )),
    ("socket-c", dict(
        prefix="SCRC", name="Socket Cap Screw",
        mat=_MAT_SUS + _MAT_SCM, weight=(0.002, 0.06),
        vendor_outsource=["V003"], vendor_purchase=["V003"],
        po_mix=[0.70, 0.25, 0.05], draw_prefix="DWG-SCRC",
        revisions=["A"],
    )),
    ("slotted_flat_head", dict(
        prefix="SFHS", name="Slotted Flat Head Screw",
        mat=_MAT_SUS, weight=(0.001, 0.03),
        vendor_outsource=["V003"], vendor_purchase=["V003"],
        po_mix=[0.70, 0.25, 0.05], draw_prefix="DWG-SFHS",
        revisions=["A"],
    )),
    ("hex_head_s", dict(
        prefix="HEXS", name="Hex Head Screw",
        mat=_MAT_SCM + _MAT_SUS, weight=(0.005, 0.12),
        vendor_outsource=["V003"], vendor_purchase=["V003"],
        po_mix=[0.70, 0.25, 0.05], draw_prefix="DWG-HEXS",
        revisions=["A"],
    )),
    ("headless", dict(
        prefix="HDLS", name="Headless Set Screw",
        mat=_MAT_SUS + _MAT_SCM, weight=(0.001, 0.02),
        vendor_outsource=["V003"], vendor_purchase=["V003"],
        po_mix=[0.70, 0.25, 0.05], draw_prefix="DWG-HDLS",
        revisions=["A"],
    )),
    ("thumb_scre", dict(
        prefix="THBS", name="Thumb Screw",
        mat=_MAT_SUS, weight=(0.005, 0.06),
        vendor_outsource=["V003"], vendor_purchase=["V003"],
        po_mix=[0.70, 0.25, 0.05], draw_prefix="DWG-THBS",
        revisions=["A"],
    )),
    ("eyesbolt", dict(
        prefix="EYEB", name="Eye Bolt",
        mat=_MAT_SUS + _MAT_STEEL, weight=(0.05, 0.60),
        vendor_outsource=["V003", "V001"], vendor_purchase=["V003"],
        po_mix=[0.70, 0.25, 0.05], draw_prefix="DWG-EYEB",
        revisions=["A"],
    )),
    ("holebolt", dict(
        prefix="HOLB", name="Hole Bolt",
        mat=_MAT_SUS + _MAT_STEEL, weight=(0.03, 0.25),
        vendor_outsource=["V003", "V001"], vendor_purchase=["V003"],
        po_mix=[0.70, 0.25, 0.05], draw_prefix="DWG-HOLB",
        revisions=["A"],
    )),
    ("cotter_pin", dict(
        prefix="COTP", name="Cotter Pin",
        mat=_MAT_SUS + _MAT_STEEL, weight=(0.001, 0.06),
        vendor_outsource=["V003"], vendor_purchase=["V003"],
        po_mix=[0.70, 0.25, 0.05], draw_prefix="DWG-COTP",
        revisions=["A"],
    )),
    ("external", dict(
        prefix="ERNG", name="External Retaining Ring",
        mat=_MAT_STEEL + _MAT_SUS, weight=(0.002, 0.06),
        vendor_outsource=["V003", "V001"], vendor_purchase=["V003"],
        po_mix=[0.70, 0.25, 0.05], draw_prefix="DWG-ERNG",
        revisions=["A"],
    )),
    # Note: "bolt" must come AFTER "eyesbolt" / "holebolt"
    ("bolt", dict(
        prefix="BOLT", name="Hex Bolt",
        mat=_MAT_SUS + _MAT_SCM, weight=(0.01, 0.20),
        vendor_outsource=["V003"], vendor_purchase=["V003"],
        po_mix=[0.70, 0.25, 0.05], draw_prefix="DWG-BOLT",
        revisions=["A"],
    )),
    ("nut", dict(
        prefix="NUT",  name="Hex Nut",
        mat=_MAT_SUS + _MAT_STEEL, weight=(0.003, 0.06),
        vendor_outsource=["V003"], vendor_purchase=["V003"],
        po_mix=[0.70, 0.25, 0.05], draw_prefix="DWG-NUT",
        revisions=["A"],
    )),
    # ---- Bearings / bushings ------------------------------------------
    ("bearing", dict(
        prefix="BRG",  name="Ball Bearing",
        mat=_MAT_BRG,  weight=(0.05, 2.00),
        vendor_outsource=["V002"], vendor_purchase=["V002"],
        po_mix=[0.70, 0.25, 0.05], draw_prefix="DWG-BRG",
        revisions=["A"],
    )),
    ("bushing_da", dict(
        prefix="DBSH", name="Damping Bushing",
        mat=_MAT_RUBBER + _MAT_STEEL, weight=(0.05, 0.60),
        vendor_outsource=["V006", "V008"], vendor_purchase=["V006"],
        po_mix=[0.70, 0.25, 0.05], draw_prefix="DWG-DBSH",
        revisions=["A"],
    )),
    # Note: "bushing_da" before "bushing"
    ("bushing", dict(
        prefix="BUSH", name="Bushing",
        mat=_MAT_BRASS + _MAT_STEEL + _MAT_PLASTIC, weight=(0.02, 0.60),
        vendor_outsource=["V001", "V008"], vendor_purchase=["V003", "V001"],
        po_mix=[0.70, 0.25, 0.05], draw_prefix="DWG-BUSH",
        revisions=["A"],
    )),
    ("collet", dict(
        prefix="COLT", name="Collet",
        mat=_MAT_BRG + _MAT_STEEL, weight=(0.02, 0.25),
        vendor_outsource=["V002", "V001"], vendor_purchase=["V002"],
        po_mix=[0.70, 0.25, 0.05], draw_prefix="DWG-COLT",
        revisions=["A"],
    )),
    # ---- Seals / gaskets -----------------------------------------------
    ("gasket", dict(
        prefix="GASK", name="Gasket",
        mat=_MAT_RUBBER + ["Compressed Fiber", "Spiral Wound"],
        weight=(0.005, 0.15),
        vendor_outsource=["V006"], vendor_purchase=["V006"],
        po_mix=[0.70, 0.25, 0.05], draw_prefix="DWG-GASK",
        revisions=["A"],
    )),
    ("grommet", dict(
        prefix="GROM", name="Grommet",
        mat=_MAT_RUBBER + _MAT_PLASTIC, weight=(0.001, 0.06),
        vendor_outsource=["V006"], vendor_purchase=["V006"],
        po_mix=[0.70, 0.25, 0.05], draw_prefix="DWG-GROM",
        revisions=["A"],
    )),
    ("o_ring", dict(
        prefix="ORING", name="O-Ring",
        mat=_MAT_RUBBER, weight=(0.001, 0.025),
        vendor_outsource=["V006"], vendor_purchase=["V006"],
        po_mix=[0.70, 0.25, 0.05], draw_prefix="DWG-ORING",
        revisions=["A"],
    )),
    # ---- Gears / power transmission ------------------------------------
    ("keyway_sha", dict(
        prefix="KWSH", name="Keyway Shaft",
        mat=_MAT_SCM + _MAT_STEEL, weight=(0.30, 12.00),
        vendor_outsource=["V001", "V008"], vendor_purchase=["V001"],
        po_mix=[0.70, 0.25, 0.05], draw_prefix="DWG-KWSH",
        revisions=["A", "B"],
    )),
    ("machine_ke", dict(
        prefix="MKEY", name="Machine Key",
        mat=_MAT_STEEL + _MAT_SUS, weight=(0.005, 0.12),
        vendor_outsource=["V001", "V003"], vendor_purchase=["V003"],
        po_mix=[0.70, 0.25, 0.05], draw_prefix="DWG-MKEY",
        revisions=["A"],
    )),
    ("miter ge", dict(
        prefix="MTRG", name="Miter Gear",
        mat=_MAT_SCM + _MAT_STEEL, weight=(0.10, 2.50),
        vendor_outsource=["V005", "V008"], vendor_purchase=["V005"],
        po_mix=[0.70, 0.25, 0.05], draw_prefix="DWG-MTRG",
        revisions=["A", "B"],
    )),
    ("idler sp", dict(
        prefix="IDSP", name="Idler Sprocket",
        mat=_MAT_STEEL + _MAT_SCM, weight=(0.20, 2.50),
        vendor_outsource=["V005", "V004"], vendor_purchase=["V005"],
        po_mix=[0.70, 0.25, 0.05], draw_prefix="DWG-IDSP",
        revisions=["A"],
    )),
    ("sprocket", dict(
        prefix="SPKT", name="Sprocket",
        mat=_MAT_STEEL + _MAT_SCM, weight=(0.20, 3.50),
        vendor_outsource=["V005", "V004"], vendor_purchase=["V005"],
        po_mix=[0.70, 0.25, 0.05], draw_prefix="DWG-SPKT",
        revisions=["A", "B"],
    )),
    ("gear rod", dict(
        prefix="GRDR", name="Gear Rod",
        mat=_MAT_SCM + _MAT_STEEL, weight=(0.20, 4.00),
        vendor_outsource=["V005", "V001"], vendor_purchase=["V005"],
        po_mix=[0.70, 0.25, 0.05], draw_prefix="DWG-GRDR",
        revisions=["A"],
    )),
    # Note: "gear" after "gear rod", "miter ge"
    ("gear", dict(
        prefix="GEAR", name="Spur Gear",
        mat=_MAT_SCM + _MAT_STEEL, weight=(0.10, 6.00),
        vendor_outsource=["V005", "V008"], vendor_purchase=["V005"],
        po_mix=[0.70, 0.25, 0.05], draw_prefix="DWG-GEAR",
        revisions=["A", "B"],
    )),
    # ---- Structural / enclosures ---------------------------------------
    ("bracket", dict(
        prefix="BKT",  name="Mounting Bracket",
        mat=_MAT_STEEL + _MAT_SUS + _MAT_AL, weight=(0.10, 4.00),
        vendor_outsource=["V007", "V008"], vendor_purchase=["V007"],
        po_mix=[0.70, 0.25, 0.05], draw_prefix="DWG-BKT",
        revisions=["A", "B", "C"],
    )),
    ("box", dict(
        prefix="ENCL", name="Enclosure Box",
        mat=_MAT_STEEL + _MAT_AL + _MAT_SUS, weight=(0.30, 6.00),
        vendor_outsource=["V007", "V008"], vendor_purchase=["V007"],
        po_mix=[0.70, 0.25, 0.05], draw_prefix="DWG-ENCL",
        revisions=["A", "B"],
    )),
    ("rectangu", dict(
        prefix="RECT", name="Rectangular Plate",
        mat=_MAT_STEEL + _MAT_SUS + _MAT_AL, weight=(0.20, 12.00),
        vendor_outsource=["V007", "V003"], vendor_purchase=["V007"],
        po_mix=[0.70, 0.25, 0.05], draw_prefix="DWG-RECT",
        revisions=["A", "B"],
    )),
    ("routing", dict(
        prefix="RTBK", name="Routing Bracket",
        mat=_MAT_STEEL + _MAT_AL, weight=(0.10, 1.80),
        vendor_outsource=["V007", "V008"], vendor_purchase=["V007"],
        po_mix=[0.70, 0.25, 0.05], draw_prefix="DWG-RTBK",
        revisions=["A"],
    )),
    ("strut ch", dict(
        prefix="STRC", name="Strut Channel",
        mat=_MAT_STEEL + _MAT_SUS, weight=(0.30, 6.00),
        vendor_outsource=["V007", "V003"], vendor_purchase=["V003"],
        po_mix=[0.70, 0.25, 0.05], draw_prefix="DWG-STRC",
        revisions=["A"],
    )),
    ("tag hold", dict(
        prefix="TAGHD", name="Tag Holder",
        mat=_MAT_SUS + _MAT_STEEL, weight=(0.02, 0.25),
        vendor_outsource=["V007", "V003"], vendor_purchase=["V003"],
        po_mix=[0.70, 0.25, 0.05], draw_prefix="DWG-TAGHD",
        revisions=["A"],
    )),
    ("webbing", dict(
        prefix="WBCL", name="Webbing Clip",
        mat=_MAT_SUS + _MAT_STEEL, weight=(0.02, 0.25),
        vendor_outsource=["V007", "V003"], vendor_purchase=["V003"],
        po_mix=[0.70, 0.25, 0.05], draw_prefix="DWG-WBCL",
        revisions=["A"],
    )),
    ("wide gri", dict(
        prefix="WDGR", name="Wide Grip",
        mat=_MAT_SUS + _MAT_STEEL, weight=(0.05, 0.60),
        vendor_outsource=["V007", "V003"], vendor_purchase=["V003"],
        po_mix=[0.70, 0.25, 0.05], draw_prefix="DWG-WDGR",
        revisions=["A"],
    )),
    # ---- Fallback ------------------------------------------------------
    ("", dict(
        prefix="PART", name="Mechanical Part",
        mat=_MAT_STEEL, weight=(0.05, 3.00),
        vendor_outsource=["V001", "V007", "V008"], vendor_purchase=["V003"],
        po_mix=[0.70, 0.25, 0.05], draw_prefix="DWG-PART",
        revisions=["A"],
    )),
]


def get_config(folder_name: str) -> dict:
    """Return the first matching category config for *folder_name*."""
    fn = folder_name.lower()
    for keyword, cfg in CATEGORY_RULES:
        if keyword in fn:
            return cfg
    return CATEGORY_RULES[-1][1]


# ---------------------------------------------------------------------------
# Tables
# ---------------------------------------------------------------------------

def create_tables():
    Base.metadata.drop_all(bind=engine)
    Base.metadata.create_all(bind=engine)


# ---------------------------------------------------------------------------
# Seed
# ---------------------------------------------------------------------------

def seed(db):
    today = datetime.date.today()

    def future(days: int) -> datetime.date:
        return today + datetime.timedelta(days=days)

    def past(years: int = 0, months: int = 0) -> datetime.date:
        yr = today.year - years
        mo = today.month - months
        while mo <= 0:
            mo += 12
            yr -= 1
        return datetime.date(yr, mo, min(today.day, calendar.monthrange(yr, mo)[1]))

    # -----------------------------------------------------------------------
    # Vendors
    # -----------------------------------------------------------------------
    vendors = [
        Vendor(vendor_id="V001", vendor_name="Yamada Precision Machining Ltd.",
               specialty="Rotary shafts, collars, precision turning",
               country="JP", rating=4.8, typical_lead_time_days=14),
        Vendor(vendor_id="V002", vendor_name="Toyo Bearing Industries Co., Ltd.",
               specialty="Rolling bearings, precision mechanical parts",
               country="JP", rating=4.9, typical_lead_time_days=7),
        Vendor(vendor_id="V003", vendor_name="McMaster-Carr Supply Company",
               specialty="Fasteners, standard hardware, consumables",
               country="US", rating=4.7, typical_lead_time_days=10),
        Vendor(vendor_id="V004", vendor_name="Misumi Group Inc.",
               specialty="Conveyor rollers, linear motion, custom standards",
               country="JP", rating=4.6, typical_lead_time_days=5),
        Vendor(vendor_id="V005", vendor_name="Hitachi Metals Machinery Co., Ltd.",
               specialty="Gears, sprockets, heat-treated components",
               country="JP", rating=4.5, typical_lead_time_days=21),
        Vendor(vendor_id="V006", vendor_name="Parker Hannifin Japan Ltd.",
               specialty="Pipe fittings, O-rings, seals, fluid control",
               country="US", rating=4.7, typical_lead_time_days=14),
        Vendor(vendor_id="V007", vendor_name="Mitsubishi Materials Corp.",
               specialty="Brackets, structural parts, sheet metal fabrication",
               country="JP", rating=4.4, typical_lead_time_days=18),
        Vendor(vendor_id="V008", vendor_name="Kyowa Industrial Co., Ltd.",
               specialty="Custom machining, prototypes, special orders",
               country="JP", rating=4.3, typical_lead_time_days=28),
    ]
    db.add_all(vendors)
    db.flush()

    # -----------------------------------------------------------------------
    # Load CAD file list (catalog or live scan)
    # -----------------------------------------------------------------------
    raw = _load_cad_files()   # list of (category, cad_file_name)

    # -----------------------------------------------------------------------
    # Build Part records
    # -----------------------------------------------------------------------
    parts: list[Part] = []
    part_cfgs: list[dict] = []        # parallel list, same index as parts
    prefix_counters: dict[str, int] = {}

    for category, cad_name in raw:
        cfg = get_config(category)
        prefix = cfg["prefix"]
        prefix_counters[prefix] = prefix_counters.get(prefix, 0) + 1
        seq = prefix_counters[prefix]
        part_id = f"{prefix}-{seq:04d}"

        # Per-file seeded RNG so the output is deterministic
        rng = random.Random(cad_name)

        mat     = rng.choice(cfg["mat"])
        weight  = round(rng.uniform(*cfg["weight"]), 3)
        rev     = rng.choice(cfg["revisions"])
        drawing = f"{cfg['draw_prefix']}-{seq:04d}"

        status_roll = rng.random()
        status = ("active" if status_roll < 0.85
                  else "under_review" if status_roll < 0.95
                  else "obsolete")

        yr = today.year - rng.randint(0, 4)
        mo = today.month - rng.randint(0, 11)
        while mo <= 0:
            mo += 12; yr -= 1
        created_at = datetime.date(yr, mo, min(today.day, calendar.monthrange(yr, mo)[1]))

        part_name = f"{cfg['name']} {part_id}"

        parts.append(Part(
            part_id=part_id,
            part_name=part_name,
            revision=rev,
            material=mat,
            weight_kg=weight,
            drawing_number=drawing,
            cad_file_name=cad_name,
            created_at=created_at,
            status=status,
        ))
        part_cfgs.append(cfg)

    db.add_all(parts)
    db.flush()

    # -----------------------------------------------------------------------
    # Sample BOM assemblies
    # Group first parts by prefix for illustration
    # -----------------------------------------------------------------------
    first_by_prefix: dict[str, str] = {}  # prefix -> part_id
    for part in parts:
        pfx = part.part_id.rsplit("-", 1)[0]
        if pfx not in first_by_prefix:
            first_by_prefix[pfx] = part.part_id

    def bom_if_exists(parent_prefix: str, child_prefix: str, qty: int):
        parent = first_by_prefix.get(parent_prefix)
        child  = first_by_prefix.get(child_prefix)
        if parent and child and parent != child:
            return PartStructure(parent_part_id=parent, child_part_id=child, quantity=qty)
        return None

    bom_candidates = [
        # Conveyor roller assembly
        bom_if_exists("ROLL", "SHFT",  1),
        bom_if_exists("ROLL", "BRG",   2),
        bom_if_exists("ROLL", "COLL",  2),
        bom_if_exists("ROLL", "BOLT",  4),
        bom_if_exists("ROLL", "NUT",   4),
        bom_if_exists("ROLL", "WSHR",  8),
        # Gear drive unit
        bom_if_exists("GEAR", "KWSH",  1),
        bom_if_exists("GEAR", "BRG",   2),
        bom_if_exists("GEAR", "BUSH",  1),
        bom_if_exists("GEAR", "HEXS",  4),
        bom_if_exists("GEAR", "MKEY",  1),
        # Sprocket drive
        bom_if_exists("SPKT", "SHFT",  1),
        bom_if_exists("SPKT", "BRG",   2),
        bom_if_exists("SPKT", "SCRS",  4),
        # Pipe assembly
        bom_if_exists("PIPE", "FTG",   2),
        bom_if_exists("PIPE", "JNT",   1),
        bom_if_exists("PIPE", "ORING", 4),
        bom_if_exists("PIPE", "GASK",  2),
        bom_if_exists("PIPE", "BKT",   2),
        bom_if_exists("PIPE", "BOLT",  8),
        # Enclosure
        bom_if_exists("ENCL", "BKT",   4),
        bom_if_exists("ENCL", "SCRS",  8),
        bom_if_exists("ENCL", "GROM",  4),
    ]
    bom = [b for b in bom_candidates if b is not None]
    db.add_all(bom)
    db.flush()

    # -----------------------------------------------------------------------
    # Production orders  (0–5 per part, 70/25/5 mix)
    # -----------------------------------------------------------------------
    QUALITY_WEIGHTS = [0.78, 0.17, 0.05]   # passed / pending / failed
    QUALITY_CHOICES = ["passed", "pending", "failed"]

    # Number of orders distribution (weights for 0,1,2,3,4,5)
    ORDER_COUNT_WEIGHTS = [8, 22, 28, 22, 12, 8]

    orders: list[ProductionOrder] = []
    order_seq = 1

    for part, cfg in zip(parts, part_cfgs):
        rng = random.Random(part.cad_file_name + "_po")

        n_orders = rng.choices(range(6), weights=ORDER_COUNT_WEIGHTS)[0]

        for _ in range(n_orders):
            # Production type
            roll = rng.random()
            pmix = cfg["po_mix"]
            if roll < pmix[0]:
                ptype     = "in_house"
                vendor_id = None
            elif roll < pmix[0] + pmix[1]:
                ptype     = "outsource"
                vendor_id = rng.choice(cfg["vendor_outsource"])
            else:
                ptype     = "purchase"
                vendor_id = rng.choice(cfg["vendor_purchase"])

            qty       = rng.randint(5, 300)
            unit_cost = round(rng.uniform(20.0, 8000.0), 0)
            lead_days = rng.randint(5, 45)
            del_days  = rng.randint(7, 120)
            quality   = rng.choices(QUALITY_CHOICES, weights=QUALITY_WEIGHTS)[0]

            orders.append(ProductionOrder(
                order_id        = f"PO-{order_seq:06d}",
                part_id         = part.part_id,
                production_type = ptype,
                vendor_id       = vendor_id,
                quantity        = qty,
                unit_cost_jpy   = float(unit_cost),
                lead_time_days  = lead_days,
                delivery_date   = today + datetime.timedelta(days=del_days),
                quality_result  = quality,
                notes           = None,
            ))
            order_seq += 1

    db.add_all(orders)
    db.flush()

    # -----------------------------------------------------------------------
    # Purchase items – one catalog entry per part that has any "purchase" order
    # -----------------------------------------------------------------------
    purchase_parts: set[str] = {
        o.part_id for o in orders if o.production_type == "purchase"
    }
    purchase_items: list[PurchaseItem] = []
    pi_seq = 1

    for part, cfg in zip(parts, part_cfgs):
        if part.part_id not in purchase_parts:
            continue
        rng = random.Random(part.cad_file_name + "_pi")
        vendor_id = rng.choice(cfg["vendor_purchase"])
        catalog_price = round(rng.uniform(10.0, 5000.0), 0)
        moq  = rng.choice([10, 25, 50, 100, 200, 500])
        lead = rng.randint(5, 30)

        purchase_items.append(PurchaseItem(
            item_id          = f"PI-{pi_seq:05d}",
            part_id          = part.part_id,
            vendor_id        = vendor_id,
            catalog_price_jpy= float(catalog_price),
            min_order_qty    = moq,
            lead_time_days   = lead,
        ))
        pi_seq += 1

    db.add_all(purchase_items)
    db.commit()

    # -----------------------------------------------------------------------
    # Summary
    # -----------------------------------------------------------------------
    total_po = len(orders)
    in_house = sum(1 for o in orders if o.production_type == "in_house")
    outsource= sum(1 for o in orders if o.production_type == "outsource")
    purchase = sum(1 for o in orders if o.production_type == "purchase")

    print(
        f"\nDatabase seeded successfully:\n"
        f"  Vendors          : {len(vendors)}\n"
        f"  Parts            : {len(parts)}\n"
        f"  BOM rows         : {len(bom)}\n"
        f"  Production orders: {total_po} "
        f"(in_house {in_house} / outsource {outsource} / purchase {purchase})\n"
        f"  Purchase items   : {len(purchase_items)}\n"
    )


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    print("Creating tables …")
    create_tables()
    db = SessionLocal()
    try:
        seed(db)
    except Exception as exc:
        db.rollback()
        print(f"ERROR: {exc}")
        raise
    finally:
        db.close()
    print("Database ready.")
